-- Live Performance Optimization Engine 20260702400000
CREATE TYPE "PerfOptJobType" AS ENUM ('DAILY_REVIEW', 'MISSED_OPPORTUNITY', 'LATE_ENTRY_ANALYZE', 'EARLY_EXIT_ANALYZE', 'LATE_EXIT_ANALYZE', 'TRADE_QUALITY_SCORE', 'STRATEGY_RANKING', 'COIN_RANKING', 'MARKET_CONDITION_ANALYZE', 'GENERATE_RECOMMENDATIONS', 'PARAMETER_RECOMMENDATIONS', 'PAPER_LIVE_COMPARE', 'TIMELINE_UPDATE', 'SUCCESS_METRICS', 'TRADE_ANALYZE');
CREATE TYPE "PerfOptRecommendationTarget" AS ENUM ('SCANNER', 'ENTRY_AI', 'EXIT_AI', 'STRATEGY_SELECTOR', 'RISK_ENGINE', 'LEARNING_ENGINE', 'GENERAL');
CREATE TYPE "PerfOptTimelinePeriod" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY');

CREATE TABLE "PerfOptPerformanceReview" ("id" TEXT NOT NULL, "reviewKey" TEXT NOT NULL, "reviewDate" DATE NOT NULL, "tradeCount" INTEGER NOT NULL DEFAULT 0, "winningTrades" INTEGER NOT NULL DEFAULT 0, "losingTrades" INTEGER NOT NULL DEFAULT 0, "averageProfit" DOUBLE PRECISION NOT NULL DEFAULT 0, "averageLoss" DOUBLE PRECISION NOT NULL DEFAULT 0, "profitFactor" DOUBLE PRECISION NOT NULL DEFAULT 0, "expectancy" DOUBLE PRECISION NOT NULL DEFAULT 0, "drawdown" DOUBLE PRECISION NOT NULL DEFAULT 0, "winRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "capitalGrowth" DOUBLE PRECISION NOT NULL DEFAULT 0, "rejectedTrades" INTEGER NOT NULL DEFAULT 0, "metadata" JSONB, "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptPerformanceReview_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptTradeQuality" ("id" TEXT NOT NULL, "qualityKey" TEXT NOT NULL, "positionId" TEXT, "symbol" TEXT NOT NULL, "entryQuality" DOUBLE PRECISION NOT NULL DEFAULT 0, "exitQuality" DOUBLE PRECISION NOT NULL DEFAULT 0, "timingScore" DOUBLE PRECISION NOT NULL DEFAULT 0, "riskScore" DOUBLE PRECISION NOT NULL DEFAULT 0, "decisionQuality" DOUBLE PRECISION NOT NULL DEFAULT 0, "executionQuality" DOUBLE PRECISION NOT NULL DEFAULT 0, "overallScore" DOUBLE PRECISION NOT NULL DEFAULT 0, "metadata" JSONB, "scoredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptTradeQuality_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptMissedOpportunity" ("id" TEXT NOT NULL, "opportunityKey" TEXT NOT NULL, "symbol" TEXT NOT NULL, "decisionId" TEXT, "scannerPassed" BOOLEAN NOT NULL DEFAULT true, "wasRejected" BOOLEAN NOT NULL DEFAULT true, "maxPossibleProfitPct" DOUBLE PRECISION NOT NULL DEFAULT 0, "actualProfitPct" DOUBLE PRECISION NOT NULL DEFAULT 0, "missedProfitPct" DOUBLE PRECISION NOT NULL DEFAULT 0, "rejectReason" TEXT, "confidence" DOUBLE PRECISION, "metadata" JSONB, "detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptMissedOpportunity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptEntryOptimization" ("id" TEXT NOT NULL, "optimizationKey" TEXT NOT NULL, "positionId" TEXT, "symbol" TEXT NOT NULL, "optimizationType" TEXT NOT NULL DEFAULT 'LATE_ENTRY', "earlierEntryPrice" DOUBLE PRECISION, "actualEntryPrice" DOUBLE PRECISION NOT NULL, "lostOpportunityPct" DOUBLE PRECISION NOT NULL DEFAULT 0, "metadata" JSONB, "analyzedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptEntryOptimization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptExitOptimization" ("id" TEXT NOT NULL, "optimizationKey" TEXT NOT NULL, "positionId" TEXT, "symbol" TEXT NOT NULL, "optimizationType" TEXT NOT NULL DEFAULT 'EARLY_EXIT', "bestExitPrice" DOUBLE PRECISION, "actualExitPrice" DOUBLE PRECISION NOT NULL, "peakProfitPct" DOUBLE PRECISION, "actualProfitPct" DOUBLE PRECISION, "lostProfitPct" DOUBLE PRECISION NOT NULL DEFAULT 0, "profitGivebackPct" DOUBLE PRECISION NOT NULL DEFAULT 0, "metadata" JSONB, "analyzedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptExitOptimization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptStrategyPerformanceHistory" ("id" TEXT NOT NULL, "historyKey" TEXT NOT NULL, "strategyType" TEXT NOT NULL, "winRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "profitFactor" DOUBLE PRECISION NOT NULL DEFAULT 0, "expectancy" DOUBLE PRECISION NOT NULL DEFAULT 0, "averageReturn" DOUBLE PRECISION NOT NULL DEFAULT 0, "maxDrawdown" DOUBLE PRECISION NOT NULL DEFAULT 0, "tradeCount" INTEGER NOT NULL DEFAULT 0, "rank" INTEGER, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptStrategyPerformanceHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptCoinPerformance" ("id" TEXT NOT NULL, "performanceKey" TEXT NOT NULL, "symbol" TEXT NOT NULL, "category" TEXT, "narrative" TEXT, "winRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "profitFactor" DOUBLE PRECISION NOT NULL DEFAULT 0, "totalProfitPct" DOUBLE PRECISION NOT NULL DEFAULT 0, "tradeCount" INTEGER NOT NULL DEFAULT 0, "rank" INTEGER, "isWorst" BOOLEAN NOT NULL DEFAULT false, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptCoinPerformance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptRecommendation" ("id" TEXT NOT NULL, "recommendationKey" TEXT NOT NULL, "target" "PerfOptRecommendationTarget" NOT NULL DEFAULT 'GENERAL', "title" TEXT NOT NULL, "description" TEXT NOT NULL, "expectedBenefit" TEXT NOT NULL, "confidence" DOUBLE PRECISION NOT NULL DEFAULT 50, "supportingEvidence" JSONB, "historicalSuccess" DOUBLE PRECISION, "applied" BOOLEAN NOT NULL DEFAULT false, "metadata" JSONB, "recommendedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptRecommendation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptOptimizationHistory" ("id" TEXT NOT NULL, "historyKey" TEXT NOT NULL, "actionType" TEXT NOT NULL, "target" TEXT NOT NULL, "summary" TEXT NOT NULL, "beforeMetrics" JSONB, "afterMetrics" JSONB, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptOptimizationHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptTimeline" ("id" TEXT NOT NULL, "timelineKey" TEXT NOT NULL, "period" "PerfOptTimelinePeriod" NOT NULL, "periodStart" TIMESTAMP(3) NOT NULL, "periodEnd" TIMESTAMP(3) NOT NULL, "metrics" JSONB NOT NULL, "tradeEvolution" JSONB, "strategyEvolution" JSONB, "metadata" JSONB, "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptTimeline_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptSuccessMetrics" ("id" TEXT NOT NULL, "metricsKey" TEXT NOT NULL, "profitFactorTrend" DOUBLE PRECISION, "winRateTrend" DOUBLE PRECISION, "monthlyReturnTrend" DOUBLE PRECISION, "maxDrawdownTrend" DOUBLE PRECISION, "tradeQualityTrend" DOUBLE PRECISION, "missedOpportunityTrend" DOUBLE PRECISION, "avgHoldingTrend" DOUBLE PRECISION, "capitalGrowthCurve" JSONB, "metadata" JSONB, "calculatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptSuccessMetrics_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerfOptJobState" ("id" TEXT NOT NULL, "jobType" "PerfOptJobType" NOT NULL, "lastProcessedAt" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'IDLE', "metadata" JSONB, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PerfOptJobState_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "PerfOptPerformanceReview_reviewKey_key" ON "PerfOptPerformanceReview"("reviewKey");
CREATE INDEX "PerfOptPerformanceReview_reviewDate_idx" ON "PerfOptPerformanceReview"("reviewDate");
CREATE UNIQUE INDEX "PerfOptTradeQuality_qualityKey_key" ON "PerfOptTradeQuality"("qualityKey");
CREATE INDEX "PerfOptTradeQuality_symbol_scoredAt_idx" ON "PerfOptTradeQuality"("symbol", "scoredAt");
CREATE UNIQUE INDEX "PerfOptMissedOpportunity_opportunityKey_key" ON "PerfOptMissedOpportunity"("opportunityKey");
CREATE INDEX "PerfOptMissedOpportunity_symbol_detectedAt_idx" ON "PerfOptMissedOpportunity"("symbol", "detectedAt");
CREATE UNIQUE INDEX "PerfOptEntryOptimization_optimizationKey_key" ON "PerfOptEntryOptimization"("optimizationKey");
CREATE UNIQUE INDEX "PerfOptExitOptimization_optimizationKey_key" ON "PerfOptExitOptimization"("optimizationKey");
CREATE UNIQUE INDEX "PerfOptStrategyPerformanceHistory_historyKey_key" ON "PerfOptStrategyPerformanceHistory"("historyKey");
CREATE UNIQUE INDEX "PerfOptCoinPerformance_performanceKey_key" ON "PerfOptCoinPerformance"("performanceKey");
CREATE UNIQUE INDEX "PerfOptRecommendation_recommendationKey_key" ON "PerfOptRecommendation"("recommendationKey");
CREATE UNIQUE INDEX "PerfOptOptimizationHistory_historyKey_key" ON "PerfOptOptimizationHistory"("historyKey");
CREATE UNIQUE INDEX "PerfOptTimeline_timelineKey_key" ON "PerfOptTimeline"("timelineKey");
CREATE UNIQUE INDEX "PerfOptSuccessMetrics_metricsKey_key" ON "PerfOptSuccessMetrics"("metricsKey");
CREATE UNIQUE INDEX "PerfOptJobState_jobType_key" ON "PerfOptJobState"("jobType");
