module.exports = {
  apps: [
    {
      name: "kinetic-web",
      script: "npm",
      args: "run start",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env_file: ".env",
      out_file: "./logs/pm2-web.out.log",
      error_file: "./logs/pm2-web.err.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "kinetic-worker",
      script: "npm",
      args: "run worker:start",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      env_file: ".env",
      out_file: "./logs/pm2-worker.out.log",
      error_file: "./logs/pm2-worker.err.log",
      merge_logs: true,
      time: true,
    },
  ],
};
