import { describe, expect, it, beforeEach } from "vitest";
import { buildFinalCandidate, resolveMicroState } from "@/src/server/microstructure/final-ranker";
import { DEFAULT_MICRO_CONFIG } from "@/src/server/microstructure/config";
import {
  getCanonicalCandidateStore,
  resetCanonicalCandidateStoreForTests,
} from "@/src/server/candidate/candidate-store.service";
import type { FinalRankedCandidate, MicroFeatures } from "@/src/server/microstructure/types";
import type { OpportunityCandidate } from "@/src/server/opportunity/types";

function mockFeatures(overrides?: Partial<MicroFeatures>): MicroFeatures {
  return {
    takerBuyVolume1s: 100,
    takerSellVolume1s: 80,
    takerBuyVolume5s: 500,
    takerSellVolume5s: 400,
    takerBuyVolume15s: 1500,
    takerSellVolume15s: 1200,
    takerBuyVolume60s: 6000,
    takerSellVolume60s: 5200,
    netTakerFlow5s: 100,
    netTakerFlow15s: 300,
    takerBuyRatio5s: 0.56,
    takerBuyRatio15s: 0.55,
    flowImbalance3s: 0.08,
    flowImbalance5s: 0.1,
    flowImbalance15s: 0.1,
    flowImbalance60s: 0.08,
    buyFlowAcceleration: 10,
    sellFlowAcceleration: 4,
    netFlowAcceleration: 6,
    tradeRate1s: 2,
    tradeRate5s: 3,
    tradeRate15s: 2,
    tradeRateAcceleration: 1,
    avgTradeNotional5s: 40,
    avgTradeNotional15s: 35,
    avgTradeNotional60s: 30,
    largeBuyTradeRate: 0.2,
    largeSellTradeRate: 0.1,
    largeBuyNotional: 1000,
    largeSellNotional: 600,
    spreadBps: 20,
    spreadAbsolute: 0.1,
    topBookImbalance: 0.1,
    depthImbalance5bps: 0.1,
    depthImbalance10bps: 0.1,
    depthImbalance25bps: 0.1,
    bidLiquidity: 2000,
    askLiquidity: 2000,
    askDepthChange: -10,
    askDepletionRate: 0.09,
    askReloadRate: 0.03,
    bidPersistence: 0.75,
    bidReload: 0.08,
    bidWithdrawal: 0.08,
    liquidityVolatility: 0.1,
    largeAskAppearedThenRemoved: 0,
    largeBidAppearedThenRemoved: 0,
    priceChangePerBuyNotional: 0.2,
    sellAbsorption: 0,
    buyAbsorption: 0.1,
    crossLayerConfirmation: 0.2,
    priceFlowDivergence: 0,
    priceVolumeDivergence: 0,
    priceBookDivergence: 0,
    microExhaustion: 0.1,
    breakoutHoldTime: 6,
    postBreakoutFlow: 0.2,
    breakoutRetestQuality: 0.3,
    failedBreakout: 0,
    expectedSlippageBps: 12,
    depthToIntendedSize: 5,
    lastAggTradeAt: Date.now() - 1000,
    lastBookTickerAt: Date.now() - 900,
    lastDepthAt: Date.now() - 900,
    tradeCount: 12,
    ...overrides,
  };
}

function mockOpportunity(now: number): OpportunityCandidate {
  return {
    candidateId: "cand-1",
    symbol: "BTCUSDT",
    primaryLane: "EARLY",
    secondaryEvidence: ["STEADY"],
    score: 70,
    laneScores: { EARLY: 70, STEADY: 55, MOMENTUM: 40, CONTINUATION: 30 },
    breakdown: {
      priceVelocity: 10,
      priceAcceleration: 10,
      volumeAcceleration: 10,
      relativeVolume: 10,
      relativeStrength: 10,
      breakout: 10,
      compressionExpansion: 10,
      consistency: 10,
      retracementQuality: 10,
      exhaustion: 0,
      chaseControl: 10,
      liquidity: 10,
    },
    features: {
      return1s: 0.1,
      return5s: 0.2,
      return15s: 0.3,
      return30s: 0.4,
      return1m: 0.5,
      return3m: 0.7,
      return5m: 0.9,
      return15m: 1.2,
      change24h: 1.5,
      velocity5s: 0.1,
      velocity15s: 0.1,
      velocity30s: 0.1,
      velocity1m: 0.1,
      priceAccelerationShort: 0.1,
      priceAccelerationMedium: 0.1,
      accelerationConsistency: 0.5,
      volume1m: 1000,
      volume3m: 3000,
      volume5m: 5000,
      rvol1m: 1.2,
      rvol3m: 1.1,
      rvol5m: 1.1,
      volumeAcceleration: 0.2,
      relativeStrengthBTC1m: 0.1,
      relativeStrengthBTC5m: 0.1,
      relativeStrengthMarket: 0.1,
      distanceTo3mHigh: 0.2,
      distanceTo5mHigh: 0.2,
      breakout3m: 0.3,
      breakout5m: 0.3,
      compressionScore: 0.3,
      expansionScore: 0.4,
      maxRetracement: 0.1,
      retracementRatio: 0.2,
      recoverySpeed: 0.2,
      momentumConsistency: 0.4,
      exhaustionScore: 0.1,
      chaseRisk: 0.1,
      quoteVolume24h: 5_000_000,
    },
    reasonCodes: ["EARLY_PRICE_ACCELERATION"],
    state: "HOT",
    firstDetectedAt: now - 3000,
    firstDetectionPrice: 100,
    lastScoreAt: now - 1000,
    lastEvidenceAt: now - 1000,
    currentPrice: 100.4,
    scansWithoutEvidence: 0,
    deepSubscribed: false,
  };
}

describe("micro lifecycle fixes", () => {
  beforeEach(() => {
    resetCanonicalCandidateStoreForTests();
  });

  it("warming candidate NOT_EXECUTION_READY olmaz", () => {
    const store = getCanonicalCandidateStore();
    store.createCandidate({
      candidateId: "warm-1",
      symbol: "ETHUSDT",
      lane: "EARLY",
      detectedAt: Date.now() - 1_000,
      detectedPrice: 50,
    });
    const warmedRow = {
      candidateId: "warm-1",
      symbol: "ETHUSDT",
      lane: "EARLY",
      state: "WARMING",
      firstDetectedAt: Date.now() - 1000,
      firstDetectionPrice: 50,
      opportunityScore: 60,
      microScore: 40,
      microBreakdown: {} as FinalRankedCandidate["microBreakdown"],
      liquidityScore: 55,
      executionQuality: 55,
      ai: { status: "NO_OPINION", decision: "NEUTRAL", modifier: 0, reason: "test" },
      tdi: { role: "SHADOW", decision: "NEUTRAL", agreesWithCanonical: null, canReject: false },
      finalScore: 45,
      smoothedScore: 45,
      rank: 1,
      confidence: 50,
      reasonCodes: ["MICRO_WARMING"],
      warnings: ["MICRO_WARMING"],
      hardReject: null,
      hotAt: Date.now() - 500,
      microReadyAt: null,
      currentPrice: 50,
      features: mockFeatures(),
      deepSubscribed: true,
      timing: {
        hotAt: Date.now() - 500,
        deepSubscribeRequestedAt: Date.now() - 450,
        deepActiveAt: Date.now() - 420,
        firstAggTradeAt: Date.now() - 410,
        firstBookTickerAt: Date.now() - 405,
        microWarmupStartedAt: Date.now() - 400,
        microDataReadyAt: null,
        microAnalyzedAt: Date.now(),
        terminalAt: null,
        subscribeActivationLatencyMs: 30,
        firstDeepEventLatencyMs: 90,
        warmupDurationMs: null,
        hotToMicroAnalyzeLatencyMs: 500,
      },
      opportunityBreakdown: {} as FinalRankedCandidate["opportunityBreakdown"],
    } as unknown as FinalRankedCandidate;
    store.ingestMicroEvaluation({
      result: {
        evaluatedAt: Date.now(),
        durationMs: 4,
        ranked: [warmedRow],
        hotCount: 1,
        warmingCount: 1,
        confirmedCount: 0,
        executionReadyCount: 0,
        expiredCount: 0,
        deepSubscriptions: 1,
        restCalls: 0,
      },
      microInstanceId: "micro-test",
      ttlMs: 120000,
    });
    expect(store.getCandidate("warm-1")?.state).toBe("MICRO_WARMING");
  });

  it("warming sonra data-ready olunca re-evaluate edilir", () => {
    const state = resolveMicroState({
      previous: "WARMING",
      hotAt: 1000,
      now: 3000,
      config: DEFAULT_MICRO_CONFIG,
      warmed: true,
      stale: false,
      hardReject: null,
      microScore: 66,
      executionQuality: 62,
      finalScore: 72,
      spreadBps: 20,
    });
    expect(state).toBe("EXECUTION_READY");
  });

  it("stale hesaplamasi ms tabanli calisir", () => {
    const now = Date.now();
    const opportunity = mockOpportunity(now);
    const recent = buildFinalCandidate({
      opportunity,
      features: mockFeatures({ lastAggTradeAt: now - 4000, lastBookTickerAt: now - 3500 }),
      microScore: 66,
      breakdown: {
        takerBuyRatio: 1,
        buyFlowAcceleration: 1,
        tradeAcceleration: 1,
        askDepletion: 1,
        bidSupport: 1,
        depthImbalance: 1,
        breakoutAcceptance: 1,
        spreadQuality: 1,
        exhaustion: 0,
        divergence: 0,
      },
      liquidityScore: 60,
      executionQuality: 60,
      ai: { status: "NO_OPINION", decision: "NEUTRAL", modifier: 0, reason: "test" },
      hotAt: now - 6000,
      now,
      config: DEFAULT_MICRO_CONFIG,
      hardReject: null,
      tdiDecision: "NEUTRAL",
      deepSubscribed: true,
    });
    const stale = buildFinalCandidate({
      opportunity: { ...opportunity, candidateId: "cand-2" },
      features: mockFeatures({ lastAggTradeAt: now - 6500, lastBookTickerAt: now - 6200 }),
      microScore: 66,
      breakdown: recent.microBreakdown,
      liquidityScore: 60,
      executionQuality: 60,
      ai: { status: "NO_OPINION", decision: "NEUTRAL", modifier: 0, reason: "test" },
      hotAt: now - 6000,
      now,
      config: DEFAULT_MICRO_CONFIG,
      hardReject: null,
      tdiDecision: "NEUTRAL",
      deepSubscribed: true,
    });
    expect(recent.reasonCodes.includes("MICRO_DATA_STALE")).toBe(false);
    expect(stale.reasonCodes.includes("MICRO_DATA_STALE")).toBe(true);
  });
});
