export const REPLAY_EVENTS = {
  REPLAY_QUEUED: "REPLAY_QUEUED",
  REPLAY_STARTED: "REPLAY_STARTED",
  REPLAY_COMPLETED: "REPLAY_COMPLETED",
  REPLAY_FAILED: "REPLAY_FAILED",
  REPLAY_SKIPPED: "REPLAY_SKIPPED",
  MISSED_OPPORTUNITY_DETECTED: "MISSED_OPPORTUNITY_DETECTED",
  STATISTICS_AGGREGATED: "STATISTICS_AGGREGATED",
  WEIGHT_RECOMMENDATIONS_GENERATED: "WEIGHT_RECOMMENDATIONS_GENERATED",
  REJECT_ACCURACY_COMPUTED: "REJECT_ACCURACY_COMPUTED",
} as const;

export type ReplayEventType = (typeof REPLAY_EVENTS)[keyof typeof REPLAY_EVENTS];

export const REPLAY_QUEUE_NAME = "decision-replay";

export const REPLAY_QUEUE_JOBS = {
  REPLAY_SINGLE: "REPLAY_SINGLE",
  REPLAY_BATCH: "REPLAY_BATCH",
  REPLAY_DAILY: "REPLAY_DAILY",
  REPLAY_WEEKLY: "REPLAY_WEEKLY",
  REPLAY_MONTHLY: "REPLAY_MONTHLY",
  EVALUATE_REJECTED: "EVALUATE_REJECTED",
  SCAN_MISSED_OPPORTUNITIES: "SCAN_MISSED_OPPORTUNITIES",
  AGGREGATE_STATISTICS: "AGGREGATE_STATISTICS",
} as const;
