export const MARKET_INTEL_EVENTS = {
  SNAPSHOT_CAPTURED: "SNAPSHOT_CAPTURED",
  SNAPSHOT_VALIDATED: "SNAPSHOT_VALIDATED",
  SNAPSHOT_COMPRESSED: "SNAPSHOT_COMPRESSED",
  SNAPSHOT_CLEANUP: "SNAPSHOT_CLEANUP",
  SNAPSHOT_REPLAY: "SNAPSHOT_REPLAY",
  HISTORICAL_AGGREGATED: "HISTORICAL_AGGREGATED",
} as const;

export const MARKET_INTEL_QUEUE = "market-intelligence";
