import { z } from "zod";

const boolFromEnv = (defaultValue: boolean) =>
  z
    .preprocess((value) => {
      if (value === undefined || value === null || value === "") return undefined;
      if (typeof value === "boolean") return value;
      if (typeof value === "number") return value === 1;
      if (typeof value === "string") {
        const normalized = value.trim().toLowerCase();
        if (["1", "true", "yes", "on"].includes(normalized)) return true;
        if (["0", "false", "no", "off"].includes(normalized)) return false;
      }
      return value;
    }, z.boolean())
    .default(defaultValue);

const envSchema = z.object({
  EXCHANGE_PROVIDER: z.enum(["binance", "okx"]).default("binance"),
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  APP_ENV: z.enum(["dev", "stage", "prod"]).default("dev"),
  NEXT_PUBLIC_API_BASE_URL: z.string().url().optional(),
  NEXT_DISABLE_BROWSER_SOURCEMAPS: boolFromEnv(true),
  STARTUP_STRICT_ENV: boolFromEnv(false),
  RUN_MIGRATIONS_ON_BOOT: boolFromEnv(false),
  RUN_SEED_ON_BOOT: boolFromEnv(false),
  ENABLE_SEPARATE_WORKER: boolFromEnv(false),
  APP_ROLE: z.enum(["web", "worker"]).default("web"),
  DATABASE_URL: z.string().optional(),
  REDIS_URL: z.string().optional(),
  BINANCE_API_KEY: z.string().optional(),
  BINANCE_API_SECRET: z.string().optional(),
  BINANCE_GLOBAL_API_KEY: z.string().optional(),
  BINANCE_GLOBAL_API_SECRET: z.string().optional(),
  BINANCE_GLOBAL_HTTP_BASE: z.string().default("https://api.binance.com"),
  BINANCE_PLATFORM: z.enum(["global", "tr"]).default("tr"),
  BINANCE_ENV: z.enum(["testnet", "live"]).default("testnet"),
  BINANCE_TR_HTTP_BASE: z.string().default("https://www.binance.tr"),
  BINANCE_DRY_RUN: boolFromEnv(true),
  BINANCE_TIMEOUT_MS: z.coerce.number().default(5000),
  BINANCE_PUBLIC_HTTP_BASES: z
    .string()
    .default("https://www.binance.tr"),
  BINANCE_TAKER_FEE_RATE: z.coerce.number().default(0.001),
  BINANCE_MAKER_FEE_RATE: z.coerce.number().default(0.0009),
  OKX_API_KEY: z.string().optional(),
  OKX_API_SECRET: z.string().optional(),
  OKX_API_PASSPHRASE: z.string().optional(),
  OKX_ENV: z.enum(["testnet", "live"]).default("live"),
  OKX_DRY_RUN: boolFromEnv(true),
  OKX_TIMEOUT_MS: z.coerce.number().default(5000),
  OKX_TAKER_FEE_RATE: z.coerce.number().default(0.001),
  OKX_MAKER_FEE_RATE: z.coerce.number().default(0.0008),
  AI_ENABLED_PROVIDERS: z.string().default("provider-1,provider-2,provider-3"),
  AI_PROVIDER_1_NAME: z.string().default("OpenAI"),
  AI_PROVIDER_2_NAME: z.string().default("Claude"),
  AI_PROVIDER_3_NAME: z.string().default("Gemini"),
  AI_PROVIDER_1_API_KEY: z.string().optional(),
  AI_PROVIDER_2_API_KEY: z.string().optional(),
  AI_PROVIDER_3_API_KEY: z.string().optional(),
  AI_REQUEST_TIMEOUT_MS: z.coerce.number().default(4000),
  AI_QUALITY_PROFILE: z.enum(["normal", "ultra", "elite"]).default("elite"),
  AI_MIN_CONFIDENCE: z.coerce.number().default(65),
  AI_MAX_RISK_SCORE: z.coerce.number().default(75),
  AI_STRICT_ANALYST_MODE: boolFromEnv(true),
  AI_REQUIRE_UNANIMOUS_BUY_SELL: boolFromEnv(true),
  AI_MIN_HEALTHY_PROVIDER_COUNT: z.coerce.number().int().default(3),
  AI_ULTRA_PRECISION_MODE: boolFromEnv(true),
  AI_SPOT_MIN_CONFIDENCE_ULTRA: z.coerce.number().default(95),
  AI_LEVERAGE_MIN_CONFIDENCE_ULTRA: z.coerce.number().default(97),
  AI_ULTRA_MAX_RISK_SCORE_SPOT: z.coerce.number().default(32),
  AI_ULTRA_MAX_RISK_SCORE_LEVERAGE: z.coerce.number().default(24),
  AI_ULTRA_MIN_TREND_AGREEMENT: z.coerce.number().default(0.96),
  AI_ULTRA_DISABLE_RELAXED_FALLBACK: boolFromEnv(true),
  AI_HYBRID_MIN_COMPOSITE_SCORE: z.coerce.number().default(62),
  AI_HYBRID_MIN_TECH_SCORE: z.coerce.number().default(58),
  AI_HYBRID_MIN_SENTIMENT_SCORE: z.coerce.number().default(52),
  AI_HYBRID_MIN_RR_RATIO: z.coerce.number().default(1.6),
  AI_HYBRID_MAX_SPREAD_PERCENT: z.coerce.number().default(0.2),
  AI_HYBRID_MAX_VOLATILITY_PERCENT: z.coerce.number().default(3.2),
  AI_HYBRID_REQUIRE_RISK_VETO: boolFromEnv(true),
  SCANNER_UNIVERSE: z.enum(["WATCHLIST", "ALL_USDT", "ALL_SPOT"]).default("ALL_SPOT"),
  SCANNER_WATCHLIST: z.string().default("BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT"),
  SCANNER_TOP_CANDIDATES: z.coerce.number().default(150),
  SCANNER_MAX_SYMBOLS: z.coerce.number().int().default(1200),
  SCANNER_CYCLE_SYMBOL_LIMIT: z.coerce.number().int().default(50),
  SCANNER_CONTEXT_CONCURRENCY: z.coerce.number().int().default(18),
  SCANNER_AI_CONCURRENCY: z.coerce.number().int().default(8),
  SCANNER_AI_EVALUATE_ALL: boolFromEnv(true),
  SCANNER_SHORT_HORIZON_SEC: z.coerce.number().int().default(120),
  SCANNER_WORKER_ENABLED: boolFromEnv(true),
  SCANNER_WORKER_INTERVAL_MS: z.coerce.number().int().default(8000),
  SCANNER_WORKER_WITH_AI: boolFromEnv(true),
  SCANNER_WORKER_PERSIST: boolFromEnv(true),
  SCANNER_MIN_VOLUME_24H: z.coerce.number().default(800_000),
  SCANNER_MAX_SPREAD_PERCENT: z.coerce.number().default(0.25),
  SCANNER_MIN_SCORE: z.coerce.number().default(40),
  EXECUTION_MODE: z.enum(["dry-run", "paper", "live"]).default("dry-run"),
  PAPER_INITIAL_BALANCE_TRY: z.coerce.number().default(100000),
  PAPER_INITIAL_BALANCE_USDT: z.coerce.number().default(2500),
  EXECUTION_ALLOW_MULTI_POSITIONS: boolFromEnv(true),
  EXECUTION_MAX_OPEN_POSITIONS: z.coerce.number().int().default(3),
  EXECUTION_DEFAULT_TAKE_PROFIT_PERCENT: z.coerce.number().default(1.2),
  EXECUTION_DEFAULT_STOP_LOSS_PERCENT: z.coerce.number().default(0.8),
  EXECUTION_DEFAULT_MAX_DURATION_SEC: z.coerce.number().int().default(600),
  EXECUTION_MANUAL_SCAN_SYMBOL_LIMIT: z.coerce.number().int().default(100),
  EXECUTION_TARGET_MIN_PROFIT_PERCENT: z.coerce.number().default(3),
  EXECUTION_TARGET_HIGH_PROFIT_PERCENT: z.coerce.number().default(10),
  EXECUTION_TARGET_MAX_PROFIT_PERCENT: z.coerce.number().default(15),
  EXECUTION_TARGET_SHORT_WINDOW_SEC: z.coerce.number().int().default(600),
  EXECUTION_TARGET_LONG_WINDOW_SEC: z.coerce.number().int().default(1200),
  EXECUTION_MONITOR_INTERVAL_MS: z.coerce.number().int().default(4000),
  EXECUTION_MIN_RR_RATIO: z.coerce.number().default(1.8),
  EXECUTION_MIN_EDGE_MULTIPLIER: z.coerce.number().default(1.25),
  EXECUTION_TRAILING_LOCK_ENABLED: boolFromEnv(true),
  EXECUTION_TRAILING_ACTIVATION_PERCENT: z.coerce.number().default(1.2),
  EXECUTION_TRAILING_DRAWDOWN_PERCENT: z.coerce.number().default(0.45),
  EXECUTION_TRAILING_MIN_LOCKED_PROFIT_PERCENT: z.coerce.number().default(0.6),
  EXECUTION_FULL_BALANCE_ENABLED: boolFromEnv(true),
  EXECUTION_BALANCE_UTILIZATION_RATE: z.coerce.number().default(0.995),
  EXECUTION_FAST_MIN_CONFIDENCE: z.coerce.number().default(90),
  EXECUTION_FAST_REQUIRE_UNANIMOUS: boolFromEnv(true),
  EXECUTION_ADAPTIVE_POLICY_ENABLED: boolFromEnv(true),
  EXECUTION_ADAPTIVE_MIN_TRADES: z.coerce.number().int().default(40),
  EXECUTION_TIMEOUT_EXTENSION_ENABLED: boolFromEnv(true),
  EXECUTION_TIMEOUT_EXTENSION_STEP_SEC: z.coerce.number().int().default(30),
  EXECUTION_TIMEOUT_EXTENSION_MAX_SEC: z.coerce.number().int().default(60),
  EXECUTION_REENTRY_AFTER_LOSS: boolFromEnv(true),
  EXECUTION_REENTRY_COOLDOWN_SEC: z.coerce.number().int().default(2),
  EXECUTION_SMART_ENTRY_ENABLED: boolFromEnv(true),
  EXECUTION_PULLBACK_TOLERANCE_PERCENT: z.coerce.number().default(0.35),
  EXECUTION_MOMENTUM_FADE_THRESHOLD: z.coerce.number().default(0.18),
  EXECUTION_REVERSE_SIGNAL_MIN_CONFIDENCE: z.coerce.number().default(92),
  EXECUTION_BLOCK_WHEN_OPEN_POSITION: boolFromEnv(true),
  EXECUTION_SAME_COIN_COOLDOWN_SEC: z.coerce.number().int().default(900),
  EXECUTION_BLOCK_HIGH_VOLATILITY_PERCENT: z.coerce.number().default(3.4),
  EXECUTION_MIN_TRADE_QUALITY_SCORE: z.coerce.number().default(60),
  EXECUTION_MIN_ADAPTIVE_SCORE: z.coerce.number().default(48),
  RISK_TOTAL_CAPITAL_TRY: z.coerce.number().default(100000),
  RISK_MAX_DAILY_LOSS_PERCENT: z.coerce.number().default(3),
  RISK_MAX_WEEKLY_LOSS_PERCENT: z.coerce.number().default(7),
  EXECUTION_SMART_TP_ENABLED: boolFromEnv(true),
  EXECUTION_SMART_TP_VOL_MULTIPLIER: z.coerce.number().default(0.35),
  EXECUTION_PARTIAL_TP_ENABLED: boolFromEnv(true),
  EXECUTION_PARTIAL_TP_FIRST_TARGET_PERCENT: z.coerce.number().default(0.8),
  EXECUTION_PARTIAL_TP_TRAIL_DRAWDOWN_PERCENT: z.coerce.number().default(0.22),
  APP_TOKEN: z.string().optional(),
  APP_TOKEN_NEXT: z.string().optional(),
  APP_ENCRYPTION_KEY: z.string().optional(),
  SECURITY_ENFORCE_ADMIN_ROLE: boolFromEnv(false),
  SECURITY_REQUIRE_CSRF: boolFromEnv(true),
  SECURITY_REQUIRE_MANUAL_CONFIRMATION: boolFromEnv(false),
});

export const env = envSchema.parse(process.env);

export const isProd = env.NODE_ENV === "production" || env.APP_ENV === "stage" || env.APP_ENV === "prod";
export const isStage = env.APP_ENV === "stage";
