import { z } from "zod";

const boolFromEnv = (defaultValue: boolean) =>
  z
    .preprocess((value) => {
      if (value === undefined || value === null || value === "") return undefined;
      if (typeof value === "boolean") return value;
      if (typeof value === "number") return value === 1;
      if (typeof value === "string") {
        const normalized = value.trim().toLowerCase();
        if (["1", "true", "yes", "on"].includes(normalized)) return true;
        if (["0", "false", "no", "off"].includes(normalized)) return false;
      }
      return value;
    }, z.boolean())
    .default(defaultValue);

const envSchema = z.object({
  EXCHANGE_PROVIDER: z.enum(["binance", "okx"]).default("binance"),
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  APP_ENV: z.enum(["dev", "stage", "prod"]).default("dev"),
  NEXT_PUBLIC_API_BASE_URL: z.string().url().optional(),
  NEXT_DISABLE_BROWSER_SOURCEMAPS: boolFromEnv(true),
  STARTUP_STRICT_ENV: boolFromEnv(false),
  RUN_MIGRATIONS_ON_BOOT: boolFromEnv(false),
  RUN_SEED_ON_BOOT: boolFromEnv(false),
  ENABLE_SEPARATE_WORKER: boolFromEnv(false),
  APP_ROLE: z.enum(["web", "worker"]).default("web"),
  DATABASE_URL: z.string().optional(),
  REDIS_URL: z.string().optional(),
  BINANCE_API_KEY: z.string().optional(),
  BINANCE_API_SECRET: z.string().optional(),
  BINANCE_GLOBAL_API_KEY: z.string().optional(),
  BINANCE_GLOBAL_API_SECRET: z.string().optional(),
  BINANCE_GLOBAL_HTTP_BASE: z.string().default("https://api.binance.com"),
  BINANCE_PLATFORM: z.enum(["global", "tr"]).default("tr"),
  BINANCE_ENV: z.enum(["testnet", "live"]).default("testnet"),
  BINANCE_TR_HTTP_BASE: z.string().default("https://www.binance.tr"),
  BINANCE_DRY_RUN: boolFromEnv(true),
  BINANCE_TIMEOUT_MS: z.coerce.number().default(5000),
  BINANCE_PUBLIC_HTTP_BASES: z
    .string()
    .default("https://api.binance.me,https://www.binance.tr"),
  BINANCE_BNB_FEE_DISCOUNT_ENABLED: boolFromEnv(false),
  BINANCE_TAKER_FEE_RATE: z.coerce.number().default(0.0015),
  BINANCE_MAKER_FEE_RATE: z.coerce.number().default(0.0009),
  OKX_API_KEY: z.string().optional(),
  OKX_API_SECRET: z.string().optional(),
  OKX_API_PASSPHRASE: z.string().optional(),
  OKX_ENV: z.enum(["testnet", "live"]).default("live"),
  OKX_DRY_RUN: boolFromEnv(true),
  OKX_TIMEOUT_MS: z.coerce.number().default(5000),
  OKX_TAKER_FEE_RATE: z.coerce.number().default(0.001),
  OKX_MAKER_FEE_RATE: z.coerce.number().default(0.0008),
  AI_ENABLED_PROVIDERS: z.string().default("provider-1,provider-2,provider-3"),
  AI_PROVIDER_1_NAME: z.string().default("OpenAI"),
  AI_PROVIDER_2_NAME: z.string().default("Claude"),
  AI_PROVIDER_3_NAME: z.string().default("Gemini"),
  AI_PROVIDER_1_MODEL: z.string().optional(),
  AI_PROVIDER_2_MODEL: z.string().optional(),
  AI_PROVIDER_3_MODEL: z.string().optional(),
  AI_PROVIDER_1_API_KEY: z.string().optional(),
  AI_PROVIDER_2_API_KEY: z.string().optional(),
  AI_PROVIDER_3_API_KEY: z.string().optional(),
  AI_REQUEST_TIMEOUT_MS: z.coerce.number().default(4000),
  AI_QUALITY_PROFILE: z.enum(["normal", "ultra", "elite"]).default("elite"),
  AI_MIN_CONFIDENCE: z.coerce.number().default(65),
  AI_MAX_RISK_SCORE: z.coerce.number().default(75),
  AI_STRICT_ANALYST_MODE: boolFromEnv(true),
  AI_REQUIRE_UNANIMOUS_BUY_SELL: boolFromEnv(false),
  AI_MIN_HEALTHY_PROVIDER_COUNT: z.coerce.number().int().default(3),
  AI_ULTRA_PRECISION_MODE: boolFromEnv(false),
  AI_SPOT_MIN_CONFIDENCE_ULTRA: z.coerce.number().default(95),
  AI_LEVERAGE_MIN_CONFIDENCE_ULTRA: z.coerce.number().default(97),
  AI_ULTRA_MAX_RISK_SCORE_SPOT: z.coerce.number().default(32),
  AI_ULTRA_MAX_RISK_SCORE_LEVERAGE: z.coerce.number().default(24),
  AI_ULTRA_MIN_TREND_AGREEMENT: z.coerce.number().default(0.96),
  AI_ULTRA_DISABLE_RELAXED_FALLBACK: boolFromEnv(false),
  AI_HYBRID_MIN_COMPOSITE_SCORE: z.coerce.number().default(62),
  AI_HYBRID_MIN_TECH_SCORE: z.coerce.number().default(58),
  AI_HYBRID_MIN_SENTIMENT_SCORE: z.coerce.number().default(52),
  AI_HYBRID_MIN_RR_RATIO: z.coerce.number().default(1.6),
  AI_HYBRID_MIN_QUALITY_STRONG: z.coerce.number().default(61),
  AI_HYBRID_MIN_EDGE_SCORE: z.coerce.number().default(70),
  AI_HYBRID_MAX_SPREAD_PERCENT: z.coerce.number().default(0.2),
  AI_HYBRID_MAX_VOLATILITY_PERCENT: z.coerce.number().default(3.2),
  AI_HYBRID_REQUIRE_RISK_VETO: boolFromEnv(true),
  MACRO_NEWS_SENTIMENT: z.enum(["POSITIVE", "NEGATIVE", "NEUTRAL"]).default("NEUTRAL"),
  MACRO_HIGH_IMPACT_NEWS: boolFromEnv(false),
  MACRO_UNCERTAINTY_LEVEL: z.coerce.number().default(0),
  MACRO_BTC_DOMINANCE_BIAS: z.coerce.number().default(0),
  SCANNER_UNIVERSE: z.enum(["WATCHLIST", "ALL_USDT", "ALL_SPOT"]).default("ALL_SPOT"),
  SCANNER_WATCHLIST: z.string().default("BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT"),
  SCANNER_TOP_CANDIDATES: z.coerce.number().default(150),
  SCANNER_MAX_SYMBOLS: z.coerce.number().int().default(1200),
  SCANNER_CYCLE_SYMBOL_LIMIT: z.coerce.number().int().default(100),
  SCANNER_CONTEXT_CONCURRENCY: z.coerce.number().int().default(18),
  SCANNER_AI_CONCURRENCY: z.coerce.number().int().default(8),
  SCANNER_AI_EVALUATE_ALL: boolFromEnv(true),
  SCANNER_SHORT_HORIZON_SEC: z.coerce.number().int().default(120),
  SCANNER_WORKER_ENABLED: boolFromEnv(true),
  SCANNER_WORKER_INTERVAL_MS: z.coerce.number().int().default(8000),
  SCANNER_WORKER_WITH_AI: boolFromEnv(true),
  SCANNER_WORKER_PERSIST: boolFromEnv(true),
  AUTO_ROUND_MAX_SELECTION_ATTEMPTS: z.coerce.number().int().min(1).max(15).default(3),
  AUTO_ROUND_SELECTION_BUDGET_SEC: z.coerce.number().int().min(300).max(3600).default(1200),
  AUTO_ROUND_HEARTBEAT_INTERVAL_MS: z.coerce.number().int().min(1000).max(10000).default(2000),
  AUTO_ROUND_SCANNER_ATTACH_MAX_WAIT_MS: z.coerce.number().int().min(1000).max(120000).default(15000),
  AUTO_ROUND_SCANNER_MAX_CYCLE_SEC: z.coerce.number().int().min(15).max(300).default(90),
  AUTO_ROUND_AI_PHASE_MAX_SEC: z.coerce.number().int().min(60).max(1800).default(900),
  AUTO_ROUND_SCAN_CYCLES: z.coerce.number().int().min(1).max(4).default(1),
  AUTO_ROUND_ASYNC_WORKER_TIMEOUT_MS: z.coerce.number().int().min(5000).max(600000).default(120_000),
  AUTO_ROUND_DISCOVERY_ITEM_TIMEOUT_MS: z.coerce.number().int().min(1000).max(120000).default(30_000),
  AUTO_ROUND_MARKET_CONTEXT_TIMEOUT_MS: z.coerce.number().int().min(3000).max(180000).default(45_000),
  AUTO_ROUND_AI_CONSENSUS_TIMEOUT_MS: z.coerce.number().int().min(5000).max(300000).default(90_000),
  AUTO_ROUND_WATCHDOG_STALE_MS: z.coerce.number().int().min(15000).max(600000).default(180_000),
  AUTO_ROUND_ASYNC_HEARTBEAT_POLL_MS: z.coerce.number().int().min(500).max(10000).default(2000),
  AUTO_ROUND_PUMP_SKIP_LEARNING_FILTER: boolFromEnv(true),
  AUTO_ROUND_PUMP_SCAN_TIMEOUT_MS: z.coerce.number().int().min(15000).max(180000).default(90_000),
  PUMP_EARLY_CATCHER_ENABLED: boolFromEnv(true),
  PUMP_EARLY_CATCHER_INTERVAL_MS: z.coerce.number().int().default(10_000),
  PUMP_EARLY_CATCHER_BATCH_SIZE: z.coerce.number().int().default(64),
  PUMP_EARLY_CATCHER_MIN_SCORE: z.coerce.number().default(52),
  PUMP_EARLY_CATCHER_MIN_MOVE_PERCENT: z.coerce.number().default(0.7),
  PUMP_EARLY_CATCHER_MAX_CHASE_PERCENT: z.coerce.number().default(7.5),
  PUMP_EARLY_ACTIVE_TTL_MS: z.coerce.number().int().default(120_000),
  PUMP_LIVE_SCAN_CACHE_MS: z.coerce.number().int().default(12_000),
  PUMP_TOP_GAINER_CONTINUATION_ENABLED: boolFromEnv(true),
  PUMP_CONTINUATION_MIN_CHANGE_24H: z.coerce.number().default(6),
  PUMP_CONTINUATION_MAX_CHANGE_24H: z.coerce.number().default(180),
  PUMP_CONTINUATION_MIN_SHORT_MOMENTUM: z.coerce.number().default(0.08),
  PUMP_CONTINUATION_MIN_FLOW: z.coerce.number().default(0.045),
  PUMP_CONTINUATION_MIN_SCORE: z.coerce.number().default(46),
  PUMP_CONTINUATION_SCAN_LIMIT: z.coerce.number().int().default(72),
  PUMP_CONTINUATION_MIN_DURATION_SEC: z.coerce.number().int().default(3600),
  PUMP_CONTINUATION_STRONG_CHANGE_24H: z.coerce.number().default(40),
  PUMP_CONTINUATION_STRONG_DURATION_SEC: z.coerce.number().int().default(5400),
  PUMP_CONTINUATION_EXTREME_CHANGE_24H: z.coerce.number().default(85),
  PUMP_CONTINUATION_EXTREME_DURATION_SEC: z.coerce.number().int().default(7200),
  PUMP_DISCOVERY_MIN_CHANGE_24H: z.coerce.number().default(4),
  PUMP_INTRADAY_ENABLED: boolFromEnv(true),
  PUMP_INTRADAY_MIN_CHANGE_24H: z.coerce.number().default(4),
  PUMP_INTRADAY_MIN_SHORT_MOMENTUM: z.coerce.number().default(0.18),
  PUMP_INTRADAY_MIN_FLOW: z.coerce.number().default(0.03),
  PUMP_INTRADAY_SCAN_LIMIT: z.coerce.number().int().default(72),
  SCANNER_MAX_CYCLE_SEC: z.coerce.number().int().default(300),
  SCANNER_MIN_VOLUME_24H: z.coerce.number().default(800_000),
  SCANNER_MAX_SPREAD_PERCENT: z.coerce.number().default(0.25),
  SCANNER_MIN_SCORE: z.coerce.number().default(40),
  EXECUTION_MODE: z.enum(["dry-run", "paper", "live"]).default("dry-run"),
  EXECUTION_AI_GATE_POLICY: z.enum(["VETO", "ADVISORY"]).default("VETO"),
  PAPER_INITIAL_BALANCE_TRY: z.coerce.number().default(100000),
  PAPER_INITIAL_BALANCE_USDT: z.coerce.number().default(2500),
  EXECUTION_ALLOW_MULTI_POSITIONS: boolFromEnv(true),
  EXECUTION_MAX_OPEN_POSITIONS: z.coerce.number().int().default(3),
  EXECUTION_DEFAULT_TAKE_PROFIT_PERCENT: z.coerce.number().default(1.2),
  EXECUTION_DEFAULT_STOP_LOSS_PERCENT: z.coerce.number().default(0.8),
  EXECUTION_PUMP_MIN_STOP_LOSS_PERCENT: z.coerce.number().default(1.8),
  EXECUTION_PUMP_STOP_LOSS_LOW_PERCENT: z.coerce.number().default(1.6),
  EXECUTION_PUMP_STOP_LOSS_MID_PERCENT: z.coerce.number().default(2.4),
  EXECUTION_PUMP_STOP_LOSS_HIGH_PERCENT: z.coerce.number().default(3.2),
  EXECUTION_PUMP_STOP_LOSS_MID_SCORE: z.coerce.number().default(72),
  EXECUTION_PUMP_STOP_LOSS_HIGH_SCORE: z.coerce.number().default(85),
  EXECUTION_DEFAULT_MAX_DURATION_SEC: z.coerce.number().int().default(600),
  EXECUTION_MANUAL_SCAN_SYMBOL_LIMIT: z.coerce.number().int().default(100),
  EXECUTION_TARGET_MIN_PROFIT_PERCENT: z.coerce.number().default(1),
  EXECUTION_TARGET_HIGH_PROFIT_PERCENT: z.coerce.number().default(10),
  EXECUTION_TARGET_MAX_PROFIT_PERCENT: z.coerce.number().default(15),
  EXECUTION_TARGET_SHORT_WINDOW_SEC: z.coerce.number().int().default(600),
  EXECUTION_TARGET_LONG_WINDOW_SEC: z.coerce.number().int().default(14400),
  EXECUTION_MONITOR_INTERVAL_MS: z.coerce.number().int().default(4000),
  EXECUTION_MIN_RR_RATIO: z.coerce.number().default(1.8),
  EXECUTION_MIN_EDGE_MULTIPLIER: z.coerce.number().default(1.25),
  EXECUTION_TRAILING_LOCK_ENABLED: boolFromEnv(true),
  EXECUTION_TRAILING_ACTIVATION_PERCENT: z.coerce.number().default(1.2),
  EXECUTION_TRAILING_DRAWDOWN_PERCENT: z.coerce.number().default(0.45),
  EXECUTION_TRAILING_MIN_LOCKED_PROFIT_PERCENT: z.coerce.number().default(0.6),
  EXECUTION_FULL_BALANCE_ENABLED: boolFromEnv(true),
  EXECUTION_BALANCE_UTILIZATION_RATE: z.coerce.number().default(0.995),
  TELEGRAM_BOT_TOKEN: z.string().optional(),
  TELEGRAM_CHAT_ID: z.string().optional(),
  EMAIL_WEBHOOK_URL: z.string().url().optional(),
  EXECUTION_FAST_MIN_CONFIDENCE: z.coerce.number().default(65),
  EXECUTION_FAST_REQUIRE_UNANIMOUS: boolFromEnv(false),
  EXECUTION_ADAPTIVE_POLICY_ENABLED: boolFromEnv(true),
  EXECUTION_ADAPTIVE_MIN_TRADES: z.coerce.number().int().default(40),
  EXECUTION_TIMEOUT_EXTENSION_ENABLED: boolFromEnv(true),
  EXECUTION_TIMEOUT_EXTENSION_STEP_SEC: z.coerce.number().int().default(30),
  EXECUTION_TIMEOUT_EXTENSION_MAX_SEC: z.coerce.number().int().default(60),
  EXECUTION_REENTRY_AFTER_LOSS: boolFromEnv(true),
  EXECUTION_REENTRY_COOLDOWN_SEC: z.coerce.number().int().default(2),
  EXECUTION_SMART_ENTRY_ENABLED: boolFromEnv(true),
  EXECUTION_PULLBACK_TOLERANCE_PERCENT: z.coerce.number().default(0.35),
  EXECUTION_MOMENTUM_FADE_THRESHOLD: z.coerce.number().default(0.18),
  EXECUTION_REVERSE_SIGNAL_MIN_CONFIDENCE: z.coerce.number().default(92),
  EXECUTION_PAPER_MIN_SOFT_EXIT_HOLD_SEC: z.coerce.number().int().default(600),
  EXECUTION_PAPER_SOFT_EXIT_CONFIRMATIONS: z.coerce.number().int().default(4),
  EXECUTION_PAPER_MAX_LOSS_CUT_PERCENT: z.coerce.number().default(0.28),
  EXECUTION_PAPER_MAX_LOSS_CUT_HOLD_SEC: z.coerce.number().int().default(720),
  EXECUTION_PAPER_PUMP_MAX_LOSS_CUT_PERCENT: z.coerce.number().default(0.48),
  EXECUTION_PAPER_PUMP_MAX_LOSS_CUT_HOLD_SEC: z.coerce.number().int().default(1200),
  EXECUTION_BLOCK_WHEN_OPEN_POSITION: boolFromEnv(true),
  EXECUTION_SAME_COIN_COOLDOWN_SEC: z.coerce.number().int().default(900),
  EXECUTION_BLOCK_HIGH_VOLATILITY_PERCENT: z.coerce.number().default(3.4),
  EXECUTION_MIN_TRADE_QUALITY_SCORE: z.coerce.number().default(60),
  EXECUTION_MIN_ADAPTIVE_SCORE: z.coerce.number().default(48),
  RISK_TOTAL_CAPITAL_TRY: z.coerce.number().default(100000),
  RISK_MAX_DAILY_LOSS_PERCENT: z.coerce.number().default(5),
  RISK_MAX_WEEKLY_LOSS_PERCENT: z.coerce.number().default(7),
  EXECUTION_SMART_TP_ENABLED: boolFromEnv(true),
  EXECUTION_SMART_TP_VOL_MULTIPLIER: z.coerce.number().default(0.35),
  EXECUTION_PARTIAL_TP_ENABLED: boolFromEnv(true),
  EXECUTION_PARTIAL_TP_FIRST_TARGET_PERCENT: z.coerce.number().default(0.8),
  EXECUTION_PARTIAL_TP_TRAIL_DRAWDOWN_PERCENT: z.coerce.number().default(0.22),
  APP_TOKEN: z.string().optional(),
  APP_TOKEN_NEXT: z.string().optional(),
  APP_ENCRYPTION_KEY: z.string().optional(),
  SECURITY_ENFORCE_ADMIN_ROLE: boolFromEnv(false),
  SECURITY_REQUIRE_CSRF: boolFromEnv(true),
  SECURITY_REQUIRE_MANUAL_CONFIRMATION: boolFromEnv(false),
  HOT_PATH_V2_FREEZE_ENABLED: boolFromEnv(true),
  HOT_PATH_LEGACY_WORKERS_ENABLED: boolFromEnv(false),
  HOT_PATH_MAX_CRITICAL_WORKERS: z.coerce.number().int().min(1).max(10).default(5),
  TRADING_CORE_S2_ENABLED: boolFromEnv(true),
  DISCOVERY_V2_TOP_N: z.coerce.number().int().min(5).max(50).default(20),
  DISCOVERY_V2_CYCLE_LIMIT: z.coerce.number().int().min(100).max(5000).default(3500),
  DISCOVERY_V2_BATCH_CONCURRENCY: z.coerce.number().int().min(4).max(64).default(24),
  DISCOVERY_V2_INTEGRATE_SCANNER: boolFromEnv(true),
  REGIME_REFRESH_INTERVAL_MS: z.coerce.number().int().min(30_000).default(120_000),
  DISCOVERY_V2_MAX_SPREAD_PERCENT: z.coerce.number().default(0.35),
  DISCOVERY_V2_MIN_VOLUME_24H: z.coerce.number().default(500_000),
  DECISION_ENGINE_V2_ENABLED: boolFromEnv(true),
  DECISION_ENGINE_V2_ML_SERVICE_URL: z.string().default("http://127.0.0.1:8091"),
  DECISION_ENGINE_V2_INFERENCE_TIMEOUT_MS: z.coerce.number().int().min(20).max(500).default(120),
  DECISION_ENGINE_V2_PREDICTION_CACHE_TTL_MS: z.coerce.number().int().min(0).max(60_000).default(5000),
  DECISION_ENGINE_V2_SHADOW_MIN_TRADES: z.coerce.number().int().min(50).max(5000).default(100),
  DECISION_ENGINE_V2_DEFAULT_ALGORITHM: z.enum(["lightgbm", "xgboost", "catboost", "gradient_boosting"]).default("lightgbm"),
  DECISION_ENGINE_V2_TRAINING_LIMIT: z.coerce.number().int().min(100).max(50_000).default(5000),
  DECISION_ENGINE_V2_FEATURE_SET_VERSION: z.string().default("v2.0.0"),
  EXECUTION_ENGINE_V2_ENABLED: boolFromEnv(true),
  EXECUTION_ENGINE_V2_ENTRY_AI_ENABLED: boolFromEnv(true),
  EXECUTION_ENGINE_V2_EXIT_AI_ENABLED: boolFromEnv(true),
  EXECUTION_ENGINE_V2_MAX_SLIPPAGE_PERCENT: z.coerce.number().min(0).max(5).default(0.35),
  EXECUTION_ENGINE_V2_VERIFICATION_TIMEOUT_MS: z.coerce.number().int().min(200).max(5000).default(1000),
  EXECUTION_ENGINE_V2_RECONCILE_INTERVAL_MS: z.coerce.number().int().min(30_000).default(120_000),
  EXECUTION_ENGINE_V2_IDEMPOTENCY_TTL_MS: z.coerce.number().int().min(60_000).default(300_000),
  LEARNING_PLATFORM_ENABLED: boolFromEnv(true),
  LEARNING_PLATFORM_DATASET_LIMIT: z.coerce.number().int().min(100).max(50_000).default(5000),
  LEARNING_PLATFORM_MIN_DATASET_ROWS: z.coerce.number().int().min(30).max(10_000).default(100),
  LEARNING_PLATFORM_FEATURE_VERSION: z.string().default("lp.v1.0.0"),
  LEARNING_PLATFORM_SCHEMA_VERSION: z.string().default("lp.schema.1"),
  LEARNING_PLATFORM_LABEL_VERSION: z.string().default("lp.labels.1"),
  LEARNING_PLATFORM_NIGHTLY_TRAIN_HOUR_UTC: z.coerce.number().int().min(0).max(23).default(2),
  LEARNING_PLATFORM_PROMOTION_MIN_SHADOW_TRADES: z.coerce.number().int().min(50).max(5000).default(100),
  PAPER_VALIDATION_PLATFORM_ENABLED: boolFromEnv(true),
  PAPER_VALIDATION_MIN_TRADES: z.coerce.number().int().min(10).max(10_000).default(100),
  PAPER_VALIDATION_MIN_PROFIT_FACTOR: z.coerce.number().min(0.5).max(10).default(1.2),
  PAPER_VALIDATION_MIN_WIN_RATE: z.coerce.number().min(0).max(100).default(45),
  PAPER_VALIDATION_MAX_DRAWDOWN_PCT: z.coerce.number().min(1).max(50).default(12),
  PAPER_VALIDATION_MIN_EXECUTION_QUALITY: z.coerce.number().min(0).max(100).default(70),
  PAPER_VALIDATION_MIN_REPLAY_INTEGRITY: z.coerce.number().min(0).max(100).default(75),
  PAPER_VALIDATION_MIN_DATA_QUALITY: z.coerce.number().min(0).max(100).default(80),
  QUANT_RESEARCH_PLATFORM_ENABLED: boolFromEnv(true),
  QUANT_RESEARCH_EXPERIMENT_BATCH_SIZE: z.coerce.number().int().min(1).max(50).default(5),
  QUANT_RESEARCH_COUNTERFACTUAL_LIMIT: z.coerce.number().int().min(10).max(500).default(100),
  QUANT_RESEARCH_WALK_FORWARD_FOLDS: z.coerce.number().int().min(3).max(20).default(5),
  QUANT_RESEARCH_MONTE_CARLO_ITERATIONS: z.coerce.number().int().min(100).max(10_000).default(1000),
  QUANT_RESEARCH_FEATURE_VERSION: z.string().default("qr.v1.0.0"),
  QUANT_RESEARCH_DATASET_VERSION: z.string().default("qr.dataset.1"),
  LIVE_TRADING_PLATFORM_ENABLED: boolFromEnv(true),
  LIVE_TRADING_REQUIRE_GO_LIVE_GATE: boolFromEnv(true),
  LIVE_TRADING_MAX_DAILY_LOSS_PCT: z.coerce.number().min(0.5).max(50).default(5),
  LIVE_TRADING_MAX_DAILY_TRADES: z.coerce.number().int().min(1).max(500).default(50),
  LIVE_TRADING_MAX_OPEN_POSITIONS: z.coerce.number().int().min(1).max(50).default(5),
  LIVE_TRADING_MAX_CONSECUTIVE_LOSSES: z.coerce.number().int().min(1).max(50).default(5),
  LIVE_TRADING_MAX_POSITION_SIZE_PCT: z.coerce.number().min(1).max(100).default(10),
  LIVE_TRADING_MAX_EXPOSURE_PCT: z.coerce.number().min(5).max(100).default(50),
  LIVE_TRADING_MAX_COIN_EXPOSURE_PCT: z.coerce.number().min(1).max(100).default(15),
  LIVE_TRADING_EXECUTION_FAILURE_THRESHOLD: z.coerce.number().int().min(1).max(100).default(5),
  LIVE_TRADING_HEALTH_INTERVAL_MS: z.coerce.number().int().min(10_000).default(60_000),
  LIVE_TRADING_RECONCILE_INTERVAL_MS: z.coerce.number().int().min(30_000).default(120_000),
  DISCORD_WEBHOOK_URL: z.string().optional(),
  SLACK_WEBHOOK_URL: z.string().optional(),
  ALERT_WEBHOOK_URL: z.string().optional(),
});

export const env = envSchema.parse(process.env);

export const isProd = env.NODE_ENV === "production" || env.APP_ENV === "stage" || env.APP_ENV === "prod";
export const isStage = env.APP_ENV === "stage";
