-- Adaptive Strategy Selection Engine 20260702390000
CREATE TYPE "StrategySelectorJobType" AS ENUM ('DETECT_REGIME', 'CLASSIFY_COIN', 'SCORE_STRATEGIES', 'SELECT_STRATEGY', 'VALIDATE_SELECTION', 'REPLAY_STRATEGY', 'BENCHMARK_STRATEGIES', 'LEARN_STRATEGIES', 'SWITCH_CHECK', 'UPDATE_KNOWLEDGE', 'PERFORMANCE_SYNC');
CREATE TYPE "AdaptiveRegimeLabel" AS ENUM ('STRONG_BULL', 'WEAK_BULL', 'STRONG_BEAR', 'WEAK_BEAR', 'RANGE', 'ACCUMULATION', 'DISTRIBUTION', 'BREAKOUT', 'FAKE_BREAKOUT', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'NEWS_RALLY', 'WHALE_DRIVEN', 'LIQUIDITY_TRAP', 'FLASH_PUMP', 'FLASH_DUMP');
CREATE TYPE "CoinClassificationType" AS ENUM ('LARGE_CAP', 'MID_CAP', 'LOW_CAP', 'MICRO_CAP', 'NEW_LISTING', 'AI_COIN', 'MEME_COIN', 'LAYER1', 'LAYER2', 'DEFI', 'RWA', 'GAMING', 'INFRASTRUCTURE', 'STABLECOIN');
CREATE TYPE "StrategySelectorType" AS ENUM ('MOMENTUM', 'BREAKOUT', 'TREND_FOLLOWING', 'PULLBACK', 'MEAN_REVERSION', 'RANGE_TRADING', 'NEWS', 'WHALE', 'LISTING', 'LOW_CAP', 'SCALP', 'SWING', 'HIGH_VOLATILITY', 'CONSERVATIVE', 'AGGRESSIVE');

CREATE TABLE "AdaptiveMarketRegime" ("id" TEXT NOT NULL, "regimeKey" TEXT NOT NULL, "symbol" TEXT, "regimeLabel" "AdaptiveRegimeLabel" NOT NULL, "regimeConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0, "bullScore" DOUBLE PRECISION, "bearScore" DOUBLE PRECISION, "rangeScore" DOUBLE PRECISION, "volatilityScore" DOUBLE PRECISION, "newsScore" DOUBLE PRECISION, "whaleScore" DOUBLE PRECISION, "evidence" JSONB, "metadata" JSONB, "detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdaptiveMarketRegime_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdaptiveStrategyProfile" ("id" TEXT NOT NULL, "profileKey" TEXT NOT NULL, "strategyType" "StrategySelectorType" NOT NULL, "displayName" TEXT NOT NULL, "description" TEXT, "confidenceThreshold" DOUBLE PRECISION NOT NULL DEFAULT 60, "momentumThreshold" DOUBLE PRECISION NOT NULL DEFAULT 50, "volumeThreshold" DOUBLE PRECISION NOT NULL DEFAULT 50, "liquidityThreshold" DOUBLE PRECISION NOT NULL DEFAULT 50, "riskThreshold" DOUBLE PRECISION NOT NULL DEFAULT 50, "expectedWinRate" DOUBLE PRECISION NOT NULL DEFAULT 50, "expectedProfitFactor" DOUBLE PRECISION NOT NULL DEFAULT 1, "historicalAccuracy" DOUBLE PRECISION NOT NULL DEFAULT 50, "compatibleRegimes" "AdaptiveRegimeLabel"[], "compatibleCoins" "CoinClassificationType"[], "metadata" JSONB, "active" BOOLEAN NOT NULL DEFAULT true, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdaptiveStrategyProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdaptiveStrategySelection" ("id" TEXT NOT NULL, "selectionKey" TEXT NOT NULL, "symbol" TEXT NOT NULL, "regimeId" TEXT, "coinClassification" "CoinClassificationType", "primaryStrategy" "StrategySelectorType" NOT NULL, "secondaryStrategy" "StrategySelectorType", "rejectedStrategies" "StrategySelectorType"[], "primaryProfileId" TEXT, "strategyConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0, "expectedSuccess" DOUBLE PRECISION NOT NULL DEFAULT 0, "expectedRisk" DOUBLE PRECISION NOT NULL DEFAULT 50, "expectedHoldMinutes" DOUBLE PRECISION, "expectedVolatility" DOUBLE PRECISION, "reasoningSummary" TEXT NOT NULL, "validationPassed" BOOLEAN NOT NULL DEFAULT false, "validationDetails" JSONB, "rankings" JSONB, "metadata" JSONB, "selectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdaptiveStrategySelection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdaptiveStrategyReplay" ("id" TEXT NOT NULL, "replayKey" TEXT NOT NULL, "selectionId" TEXT, "symbol" TEXT NOT NULL, "selectedStrategy" "StrategySelectorType" NOT NULL, "alternativeStrategy" "StrategySelectorType", "wasBestStrategy" BOOLEAN NOT NULL DEFAULT false, "additionalProfitPct" DOUBLE PRECISION, "replayVerdict" TEXT, "replayPayload" JSONB, "metadata" JSONB, "replayedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdaptiveStrategyReplay_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdaptiveStrategyPerformance" ("id" TEXT NOT NULL, "performanceKey" TEXT NOT NULL, "profileId" TEXT, "strategyType" "StrategySelectorType" NOT NULL, "symbol" TEXT, "regimeLabel" "AdaptiveRegimeLabel", "winRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "profitFactor" DOUBLE PRECISION NOT NULL DEFAULT 0, "accuracy" DOUBLE PRECISION NOT NULL DEFAULT 0, "tradeCount" INTEGER NOT NULL DEFAULT 0, "totalProfitPct" DOUBLE PRECISION NOT NULL DEFAULT 0, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdaptiveStrategyPerformance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdaptiveStrategyBenchmark" ("id" TEXT NOT NULL, "benchmarkKey" TEXT NOT NULL, "rankings" JSONB NOT NULL, "comparisons" JSONB NOT NULL, "winnerStrategy" "StrategySelectorType", "metadata" JSONB, "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdaptiveStrategyBenchmark_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdaptiveStrategySwitch" ("id" TEXT NOT NULL, "switchKey" TEXT NOT NULL, "symbol" TEXT NOT NULL, "fromStrategy" "StrategySelectorType" NOT NULL, "toStrategy" "StrategySelectorType" NOT NULL, "reason" TEXT NOT NULL, "positionOpen" BOOLEAN NOT NULL DEFAULT false, "recommended" BOOLEAN NOT NULL DEFAULT true, "applied" BOOLEAN NOT NULL DEFAULT false, "metadata" JSONB, "detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdaptiveStrategySwitch_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdaptiveStrategyKnowledge" ("id" TEXT NOT NULL, "knowledgeKey" TEXT NOT NULL, "profileId" TEXT, "strategyType" "StrategySelectorType" NOT NULL, "winningMarkets" "AdaptiveRegimeLabel"[], "losingMarkets" "AdaptiveRegimeLabel"[], "bestCoins" "CoinClassificationType"[], "worstCoins" "CoinClassificationType"[], "failureReasons" TEXT[], "historicalPerformance" JSONB, "marketCompatibility" JSONB, "metadata" JSONB, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdaptiveStrategyKnowledge_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StrategySelectorJobState" ("id" TEXT NOT NULL, "jobType" "StrategySelectorJobType" NOT NULL, "lastProcessedAt" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'IDLE', "metadata" JSONB, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "StrategySelectorJobState_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "AdaptiveMarketRegime_regimeKey_key" ON "AdaptiveMarketRegime"("regimeKey");
CREATE INDEX "AdaptiveMarketRegime_symbol_detectedAt_idx" ON "AdaptiveMarketRegime"("symbol", "detectedAt");
CREATE INDEX "AdaptiveMarketRegime_regimeLabel_detectedAt_idx" ON "AdaptiveMarketRegime"("regimeLabel", "detectedAt");
CREATE UNIQUE INDEX "AdaptiveStrategyProfile_profileKey_key" ON "AdaptiveStrategyProfile"("profileKey");
CREATE UNIQUE INDEX "AdaptiveStrategyProfile_strategyType_key" ON "AdaptiveStrategyProfile"("strategyType");
CREATE UNIQUE INDEX "AdaptiveStrategySelection_selectionKey_key" ON "AdaptiveStrategySelection"("selectionKey");
CREATE INDEX "AdaptiveStrategySelection_symbol_selectedAt_idx" ON "AdaptiveStrategySelection"("symbol", "selectedAt");
CREATE INDEX "AdaptiveStrategySelection_primaryStrategy_selectedAt_idx" ON "AdaptiveStrategySelection"("primaryStrategy", "selectedAt");
CREATE INDEX "AdaptiveStrategySelection_regimeId_idx" ON "AdaptiveStrategySelection"("regimeId");
CREATE UNIQUE INDEX "AdaptiveStrategyReplay_replayKey_key" ON "AdaptiveStrategyReplay"("replayKey");
CREATE INDEX "AdaptiveStrategyReplay_symbol_replayedAt_idx" ON "AdaptiveStrategyReplay"("symbol", "replayedAt");
CREATE INDEX "AdaptiveStrategyReplay_selectionId_idx" ON "AdaptiveStrategyReplay"("selectionId");
CREATE INDEX "AdaptiveStrategyReplay_wasBestStrategy_idx" ON "AdaptiveStrategyReplay"("wasBestStrategy");
CREATE UNIQUE INDEX "AdaptiveStrategyPerformance_performanceKey_key" ON "AdaptiveStrategyPerformance"("performanceKey");
CREATE INDEX "AdaptiveStrategyPerformance_strategyType_recordedAt_idx" ON "AdaptiveStrategyPerformance"("strategyType", "recordedAt");
CREATE INDEX "AdaptiveStrategyPerformance_regimeLabel_strategyType_idx" ON "AdaptiveStrategyPerformance"("regimeLabel", "strategyType");
CREATE INDEX "AdaptiveStrategyPerformance_profileId_idx" ON "AdaptiveStrategyPerformance"("profileId");
CREATE UNIQUE INDEX "AdaptiveStrategyBenchmark_benchmarkKey_key" ON "AdaptiveStrategyBenchmark"("benchmarkKey");
CREATE INDEX "AdaptiveStrategyBenchmark_generatedAt_idx" ON "AdaptiveStrategyBenchmark"("generatedAt");
CREATE UNIQUE INDEX "AdaptiveStrategySwitch_switchKey_key" ON "AdaptiveStrategySwitch"("switchKey");
CREATE INDEX "AdaptiveStrategySwitch_symbol_detectedAt_idx" ON "AdaptiveStrategySwitch"("symbol", "detectedAt");
CREATE UNIQUE INDEX "AdaptiveStrategyKnowledge_knowledgeKey_key" ON "AdaptiveStrategyKnowledge"("knowledgeKey");
CREATE INDEX "AdaptiveStrategyKnowledge_strategyType_idx" ON "AdaptiveStrategyKnowledge"("strategyType");
CREATE UNIQUE INDEX "StrategySelectorJobState_jobType_key" ON "StrategySelectorJobState"("jobType");

ALTER TABLE "AdaptiveStrategySelection" ADD CONSTRAINT "AdaptiveStrategySelection_regimeId_fkey" FOREIGN KEY ("regimeId") REFERENCES "AdaptiveMarketRegime"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdaptiveStrategySelection" ADD CONSTRAINT "AdaptiveStrategySelection_primaryProfileId_fkey" FOREIGN KEY ("primaryProfileId") REFERENCES "AdaptiveStrategyProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdaptiveStrategyReplay" ADD CONSTRAINT "AdaptiveStrategyReplay_selectionId_fkey" FOREIGN KEY ("selectionId") REFERENCES "AdaptiveStrategySelection"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdaptiveStrategyPerformance" ADD CONSTRAINT "AdaptiveStrategyPerformance_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "AdaptiveStrategyProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdaptiveStrategyKnowledge" ADD CONSTRAINT "AdaptiveStrategyKnowledge_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "AdaptiveStrategyProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;
