-- AOC Migration 20260702360000_autonomous_operations_center
CREATE TYPE "AocJobType" AS ENUM ('PLATFORM_HEALTH', 'TRADING_HEALTH', 'INFRASTRUCTURE_MONITOR', 'EXCHANGE_MONITOR', 'QUEUE_MONITOR', 'ANOMALY_DETECT', 'SELF_HEAL', 'ALERT_DISPATCH', 'INCIDENT_PROCESS', 'HEALTH_SCORES', 'DEPENDENCY_MAP', 'KPI_MONITOR', 'AI_HEALTH');
CREATE TYPE "IncidentSeverity" AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO');
CREATE TYPE "AlertSeverity" AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');
CREATE TYPE "AlertChannel" AS ENUM ('TELEGRAM', 'DISCORD', 'SLACK', 'EMAIL', 'WEBHOOK', 'INTERNAL');
CREATE TYPE "AnomalyType" AS ENUM ('MEMORY_LEAK', 'CPU_SPIKE', 'QUEUE_EXPLOSION', 'TRADE_DROP', 'SCANNER_FAILURE', 'API_DEGRADATION', 'REJECT_SPIKE', 'LEARNING_FAILURE', 'EXECUTION_DELAY', 'EXCHANGE_OUTAGE', 'DATABASE_SLOW', 'NETWORK_FAILURE');
CREATE TYPE "RecoveryActionType" AS ENUM ('RESTART_WORKER', 'RECONNECT_WS', 'CLEAR_DEAD_WORKER', 'RETRY_FAILED_JOB', 'RECOVER_QUEUE', 'RECONNECT_EXCHANGE', 'RELOAD_CACHE', 'RECOVER_STATE');
CREATE TYPE "IncidentStatus" AS ENUM ('OPEN', 'INVESTIGATING', 'MITIGATING', 'RESOLVED', 'CLOSED');
CREATE TYPE "HealthComponentType" AS ENUM ('APPLICATION', 'WORKER', 'DATABASE', 'QUEUE', 'API', 'EXCHANGE', 'MEMORY', 'CPU', 'DISK', 'NETWORK', 'CONTAINER', 'REDIS', 'AI', 'TRADING');

CREATE TABLE "PlatformHealth" ("id" TEXT NOT NULL, "snapshotKey" TEXT NOT NULL, "applicationScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "workerScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "databaseScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "queueScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "apiScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "exchangeScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "memoryUsageMb" DOUBLE PRECISION, "cpuUsagePct" DOUBLE PRECISION, "diskUsagePct" DOUBLE PRECISION, "networkLatencyMs" DOUBLE PRECISION, "containerHealthy" BOOLEAN NOT NULL DEFAULT true, "details" JSONB, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PlatformHealth_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InfrastructureHealth" ("id" TEXT NOT NULL, "snapshotKey" TEXT NOT NULL, "dockerHealthy" BOOLEAN NOT NULL DEFAULT true, "redisHealthy" BOOLEAN NOT NULL DEFAULT true, "rabbitMqHealthy" BOOLEAN NOT NULL DEFAULT true, "postgresHealthy" BOOLEAN NOT NULL DEFAULT true, "nginxHealthy" BOOLEAN NOT NULL DEFAULT true, "nodeHealthy" BOOLEAN NOT NULL DEFAULT true, "workerCount" INTEGER NOT NULL DEFAULT 0, "cronHealthy" BOOLEAN NOT NULL DEFAULT true, "cacheHitRate" DOUBLE PRECISION, "overallScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "details" JSONB, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InfrastructureHealth_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TradingHealth" ("id" TEXT NOT NULL, "snapshotKey" TEXT NOT NULL, "decisionRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "tradeRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "rejectRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "paperTradingActive" BOOLEAN NOT NULL DEFAULT false, "liveTradingActive" BOOLEAN NOT NULL DEFAULT false, "replayEngineScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "learningEngineScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "scannerScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "executionSuccessPct" DOUBLE PRECISION NOT NULL DEFAULT 100, "overallScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "details" JSONB, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TradingHealth_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExchangeHealthHistory" ("id" TEXT NOT NULL, "snapshotKey" TEXT NOT NULL, "exchange" TEXT NOT NULL DEFAULT 'BINANCE_SPOT', "restHealthy" BOOLEAN NOT NULL DEFAULT true, "wsHealthy" BOOLEAN NOT NULL DEFAULT true, "latencyMs" DOUBLE PRECISION NOT NULL DEFAULT 0, "heartbeatOk" BOOLEAN NOT NULL DEFAULT true, "reconnectCount" INTEGER NOT NULL DEFAULT 0, "rateLimitHits" INTEGER NOT NULL DEFAULT 0, "apiErrorCount" INTEGER NOT NULL DEFAULT 0, "missingCandles" INTEGER NOT NULL DEFAULT 0, "missingTrades" INTEGER NOT NULL DEFAULT 0, "orderFailures" INTEGER NOT NULL DEFAULT 0, "overallScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "details" JSONB, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ExchangeHealthHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Incident" ("id" TEXT NOT NULL, "incidentKey" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "severity" "IncidentSeverity" NOT NULL DEFAULT 'MEDIUM', "status" "IncidentStatus" NOT NULL DEFAULT 'OPEN', "affectedModules" TEXT[], "rootCause" TEXT, "resolution" TEXT, "postMortem" TEXT, "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), "metadata" JSONB, CONSTRAINT "Incident_pkey" PRIMARY KEY ("id"));
CREATE TABLE "IncidentTimeline" ("id" TEXT NOT NULL, "timelineKey" TEXT NOT NULL, "incidentId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "description" TEXT NOT NULL, "actor" TEXT NOT NULL DEFAULT 'AOC', "metadata" JSONB, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "IncidentTimeline_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecoveryHistory" ("id" TEXT NOT NULL, "recoveryKey" TEXT NOT NULL, "incidentId" TEXT, "actionType" "RecoveryActionType" NOT NULL, "target" TEXT NOT NULL, "success" BOOLEAN NOT NULL DEFAULT false, "errorMessage" TEXT, "metadata" JSONB, "executedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RecoveryHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HealthScore" ("id" TEXT NOT NULL, "scoreKey" TEXT NOT NULL, "infrastructureScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "tradingScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "aiScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "exchangeScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "databaseScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "queueScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "platformScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "metadata" JSONB, "calculatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HealthScore_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AlertHistory" ("id" TEXT NOT NULL, "alertKey" TEXT NOT NULL, "severity" "AlertSeverity" NOT NULL DEFAULT 'MEDIUM', "channel" "AlertChannel" NOT NULL DEFAULT 'INTERNAL', "title" TEXT NOT NULL, "message" TEXT NOT NULL, "incidentId" TEXT, "delivered" BOOLEAN NOT NULL DEFAULT false, "metadata" JSONB, "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AlertHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RootCauseAnalysis" ("id" TEXT NOT NULL, "rcaKey" TEXT NOT NULL, "incidentId" TEXT NOT NULL, "probableCause" TEXT NOT NULL, "evidence" JSONB NOT NULL, "affectedModules" TEXT[], "recoverySuggestions" TEXT[], "similarIncidentIds" TEXT[], "confidence" DOUBLE PRECISION NOT NULL DEFAULT 50, "metadata" JSONB, "analyzedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RootCauseAnalysis_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AocBusinessKpi" ("id" TEXT NOT NULL, "snapshotKey" TEXT NOT NULL, "winRate" DOUBLE PRECISION, "profitFactor" DOUBLE PRECISION, "expectancy" DOUBLE PRECISION, "sharpe" DOUBLE PRECISION, "drawdown" DOUBLE PRECISION, "averageProfit" DOUBLE PRECISION, "averageLoss" DOUBLE PRECISION, "tradeFrequency" DOUBLE PRECISION, "decisionAccuracy" DOUBLE PRECISION, "rejectAccuracy" DOUBLE PRECISION, "portfolioGrowth" DOUBLE PRECISION, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AocBusinessKpi_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AocAiHealth" ("id" TEXT NOT NULL, "snapshotKey" TEXT NOT NULL, "promptLatencyMs" DOUBLE PRECISION, "modelLatencyMs" DOUBLE PRECISION, "tokenUsage" DOUBLE PRECISION, "contextSize" DOUBLE PRECISION, "hallucinationRate" DOUBLE PRECISION, "confidenceDrift" DOUBLE PRECISION, "decisionDrift" DOUBLE PRECISION, "learningDrift" DOUBLE PRECISION, "overallScore" DOUBLE PRECISION NOT NULL DEFAULT 100, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AocAiHealth_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AocServiceDependency" ("id" TEXT NOT NULL, "graphKey" TEXT NOT NULL, "nodes" JSONB NOT NULL, "edges" JSONB NOT NULL, "criticalPath" JSONB, "metadata" JSONB, "builtAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AocServiceDependency_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AocAnomaly" ("id" TEXT NOT NULL, "anomalyKey" TEXT NOT NULL, "anomalyType" "AnomalyType" NOT NULL, "severity" "IncidentSeverity" NOT NULL DEFAULT 'MEDIUM', "description" TEXT NOT NULL, "evidence" JSONB, "resolved" BOOLEAN NOT NULL DEFAULT false, "incidentId" TEXT, "metadata" JSONB, "detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), CONSTRAINT "AocAnomaly_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AocAuditLog" ("id" TEXT NOT NULL, "auditKey" TEXT NOT NULL, "actionType" TEXT NOT NULL, "target" TEXT NOT NULL, "actor" TEXT NOT NULL DEFAULT 'AOC', "success" BOOLEAN NOT NULL DEFAULT true, "details" JSONB, "metadata" JSONB, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AocAuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AocOperationalTimeline" ("id" TEXT NOT NULL, "timelineKey" TEXT NOT NULL, "timelineType" TEXT NOT NULL, "title" TEXT NOT NULL, "entries" JSONB NOT NULL, "entryCount" INTEGER NOT NULL DEFAULT 0, "metadata" JSONB, "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AocOperationalTimeline_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AocJobState" ("id" TEXT NOT NULL, "jobType" "AocJobType" NOT NULL, "lastProcessedAt" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'IDLE', "metadata" JSONB, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AocJobState_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "PlatformHealth_snapshotKey_key" ON "PlatformHealth"("snapshotKey");
CREATE INDEX "PlatformHealth_recordedAt_idx" ON "PlatformHealth"("recordedAt");
CREATE UNIQUE INDEX "InfrastructureHealth_snapshotKey_key" ON "InfrastructureHealth"("snapshotKey");
CREATE INDEX "InfrastructureHealth_recordedAt_idx" ON "InfrastructureHealth"("recordedAt");
CREATE UNIQUE INDEX "TradingHealth_snapshotKey_key" ON "TradingHealth"("snapshotKey");
CREATE INDEX "TradingHealth_recordedAt_idx" ON "TradingHealth"("recordedAt");
CREATE UNIQUE INDEX "ExchangeHealthHistory_snapshotKey_key" ON "ExchangeHealthHistory"("snapshotKey");
CREATE INDEX "ExchangeHealthHistory_exchange_recordedAt_idx" ON "ExchangeHealthHistory"("exchange", "recordedAt");
CREATE UNIQUE INDEX "Incident_incidentKey_key" ON "Incident"("incidentKey");
CREATE INDEX "Incident_severity_status_idx" ON "Incident"("severity", "status");
CREATE INDEX "Incident_openedAt_idx" ON "Incident"("openedAt");
CREATE UNIQUE INDEX "IncidentTimeline_timelineKey_key" ON "IncidentTimeline"("timelineKey");
CREATE INDEX "IncidentTimeline_incidentId_occurredAt_idx" ON "IncidentTimeline"("incidentId", "occurredAt");
CREATE UNIQUE INDEX "RecoveryHistory_recoveryKey_key" ON "RecoveryHistory"("recoveryKey");
CREATE INDEX "RecoveryHistory_actionType_executedAt_idx" ON "RecoveryHistory"("actionType", "executedAt");
CREATE INDEX "RecoveryHistory_incidentId_idx" ON "RecoveryHistory"("incidentId");
CREATE UNIQUE INDEX "HealthScore_scoreKey_key" ON "HealthScore"("scoreKey");
CREATE INDEX "HealthScore_calculatedAt_idx" ON "HealthScore"("calculatedAt");
CREATE INDEX "HealthScore_platformScore_calculatedAt_idx" ON "HealthScore"("platformScore", "calculatedAt");
CREATE UNIQUE INDEX "AlertHistory_alertKey_key" ON "AlertHistory"("alertKey");
CREATE INDEX "AlertHistory_severity_sentAt_idx" ON "AlertHistory"("severity", "sentAt");
CREATE INDEX "AlertHistory_channel_delivered_idx" ON "AlertHistory"("channel", "delivered");
CREATE UNIQUE INDEX "RootCauseAnalysis_rcaKey_key" ON "RootCauseAnalysis"("rcaKey");
CREATE UNIQUE INDEX "RootCauseAnalysis_incidentId_key" ON "RootCauseAnalysis"("incidentId");
CREATE INDEX "RootCauseAnalysis_analyzedAt_idx" ON "RootCauseAnalysis"("analyzedAt");
CREATE UNIQUE INDEX "AocBusinessKpi_snapshotKey_key" ON "AocBusinessKpi"("snapshotKey");
CREATE INDEX "AocBusinessKpi_recordedAt_idx" ON "AocBusinessKpi"("recordedAt");
CREATE UNIQUE INDEX "AocAiHealth_snapshotKey_key" ON "AocAiHealth"("snapshotKey");
CREATE INDEX "AocAiHealth_recordedAt_idx" ON "AocAiHealth"("recordedAt");
CREATE UNIQUE INDEX "AocServiceDependency_graphKey_key" ON "AocServiceDependency"("graphKey");
CREATE INDEX "AocServiceDependency_builtAt_idx" ON "AocServiceDependency"("builtAt");
CREATE UNIQUE INDEX "AocAnomaly_anomalyKey_key" ON "AocAnomaly"("anomalyKey");
CREATE INDEX "AocAnomaly_anomalyType_resolved_detectedAt_idx" ON "AocAnomaly"("anomalyType", "resolved", "detectedAt");
CREATE UNIQUE INDEX "AocAuditLog_auditKey_key" ON "AocAuditLog"("auditKey");
CREATE INDEX "AocAuditLog_actionType_recordedAt_idx" ON "AocAuditLog"("actionType", "recordedAt");
CREATE INDEX "AocAuditLog_target_recordedAt_idx" ON "AocAuditLog"("target", "recordedAt");
CREATE UNIQUE INDEX "AocOperationalTimeline_timelineKey_key" ON "AocOperationalTimeline"("timelineKey");
CREATE INDEX "AocOperationalTimeline_timelineType_generatedAt_idx" ON "AocOperationalTimeline"("timelineType", "generatedAt");
CREATE UNIQUE INDEX "AocJobState_jobType_key" ON "AocJobState"("jobType");

ALTER TABLE "IncidentTimeline" ADD CONSTRAINT "IncidentTimeline_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecoveryHistory" ADD CONSTRAINT "RecoveryHistory_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RootCauseAnalysis" ADD CONSTRAINT "RootCauseAnalysis_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE CASCADE ON UPDATE CASCADE;
